return {
  'luk400/vim-jukit',
  lazy = true,
  ft = { 'json', 'python' },
  keys = {
    { '<leader><leader>', '<Cmd>call jukit#send#line()<CR>', mode = 'n', desc = 'Send line to REPL' },
    { '<leader>jos', '<Cmd>call jukit#splits#output()<CR>', mode = 'n', desc = 'Split output' },
    { '<CR>', '<Esc><Cmd>call jukit#send#selection()<CR>', mode = 'v', desc = 'Send selection to REPL' },
    { '<leader>jepr', "<Cmd>call jukit#convert#save_nb_to_file(1,1,'pdf')<CR>", mode = 'n', desc = 'Save to pdf (rerun cells)' },
    { '<leader>jehr', "<Cmd>call jukit#convert#save_nb_to_file(1,1,'html')<CR>", mode = 'n', desc = 'Save to html (rerun cells)' },
    { '<leader>jep', "<Cmd>call jukit#convert#save_nb_to_file(0,1,'pdf')<CR>", mode = 'n', desc = 'Save to pdf' },
    { '<leader>jeh', "<Cmd>call jukit#convert#save_nb_to_file(0,1,'html')<CR>", mode = 'n', desc = 'Save to html' },
    { '<leader>jnp', "<Cmd>call jukit#convert#notebook_convert('jupyter-notebook')<CR>", mode = 'n', desc = 'Convert py/ipynb' },
    { '<leader>K', '<Cmd>call jukit#cells#jump_to_previous_cell()<CR>', mode = 'n', desc = 'Jump to previous cell' },
    { '<leader>J', '<Cmd>call jukit#cells#jump_to_next_cell()<CR>', mode = 'n', desc = 'Jump to next cell' },
    { '<leader>jda', '<Cmd>call jukit#cells#delete_outputs(1)<CR>', mode = 'n', desc = 'Delete cell output' },
    { '<leader>jdo', '<Cmd>call jukit#cells#delete_outputs(0)<CR>', mode = 'n', desc = 'Delete cell output' },
    { '<leader>jcj', '<Cmd>call jukit#cells#move_down()<CR>', mode = 'n', desc = 'Move up' },
    { '<leader>jck', '<Cmd>call jukit#cells#move_up()<CR>', mode = 'n', desc = 'Move down' },
    { '<leader>jcm', '<Cmd>call jukit#cells#merge_below()<CR>', mode = 'n', desc = 'Merge below' },
    { '<leader>jcM', '<Cmd>call jukit#cells#merge_above()<CR>', mode = 'n', desc = 'Merge above' },
    { '<leader>jcT', '<Cmd>call jukit#cells#create_above(1)<CR>', mode = 'n', desc = 'Create above text' },
    { '<leader>jct', '<Cmd>call jukit#cells#create_below(1)<CR>', mode = 'n', desc = 'Create below text' },
    { '<leader>jcO', '<Cmd>call jukit#cells#create_above(0)<CR>', mode = 'n', desc = 'Create above code' },
    { '<leader>jco', '<Cmd>call jukit#cells#create_below(0)<CR>', mode = 'n', desc = 'Create below code' },
    { '<leader>jcs', '<Cmd>call jukit#cells#split()<CR>', mode = 'n', desc = 'Split cell' },
    { '<leader>jcd', '<Cmd>call jukit#cells#delete()<CR>', mode = 'n', desc = 'Delete cell' },
    { '<leader>jall', '<Cmd>call jukit#send#all()<CR>', mode = 'n', desc = 'Send all cells' },
    { '<leader>jcc', '<Cmd>call jukit#send#until_current_section()CR>', mode = 'n', desc = 'Send until current section' },
    { '<leader>jsl', '<Cmd>call jukit#layouts#set_layout()<CR>', mode = 'n', desc = 'Set layout' },
    { '<leader>jah', '<Cmd>call jukit#splits#toggle_auto_hist()<CR>', mode = 'n', desc = 'Toggle auto history' },
    { '<leader>jpos', '<Cmd>call jukit#ueberzug#set_default_pos()<CR>', mode = 'n', desc = 'Ueberzug, set default pos' },
    { '<leader>jso', '<Cmd>call jukit#splits#show_last_cell_output(1)<CR>', mode = 'n', desc = 'Show last cell output' },
    { '<leader>jk', '<Cmd>call jukit#splits#out_hist_scroll(0)<CR>', mode = 'n', desc = 'Scroll up in history window' },
    { '<leader>jj', '<Cmd>call jukit#splits#out_hist_scroll(1)<CR>', mode = 'n', desc = 'Scroll down in history window' },
    { '<leader>johd', '<Cmd>call jukit#splits#close_output_and_history(1)<CR>', mode = 'n', desc = 'Close output and history (Asked)' },
    { '<leader>jod', '<Cmd>call jukit#splits#close_output_split()<CR>', mode = 'n', desc = 'Close output split' },
    { '<leader>jhd', '<Cmd>call jukit#splits#close_history()<CR>', mode = 'n', desc = 'Close history' },
    { '<leader>johs', '<Cmd>call jukit#splits#output_and_history()<CR>', mode = 'n', desc = 'Open output history and split' },
    { '<leader>jhs', '<Cmd>call jukit#splits#history()<CR>', mode = 'n', desc = 'Open history split' },
    { '<leader>jts', '<Cmd>call jukit#splits#term()<CR>', mode = 'n', desc = 'Splits terminal' },
  },
}
